export const userDocuments = [
    {id: 1, category: 1, name: "Zoning Clearance Form", status: 0},
    {id: 2, category: 1, name: "Building Permit Form", status: 0},
    {id: 3, category: 1, name: "Sanitary Permit Form", status: 0},
    {id: 4, category: 1, name: "Electrical Permit Form", status: 0},
    {id: 5, category: 2, name: "Authorization Letter of Special Power of Attorney from Owner to Submit, follow-up, and receive approved permits (for representative only)'", status: 0},
    {id: 6, category: 2, name: "Filing Fee proof of payment (receipt)", status: 0},
    {id: 7, category: 2, name: "Tax Declaration from City Assessor\'s Office with Documentary Stamp from City Treasurers Office", status: 0},
    {id: 8, category: 2, name: "Latest Quarter of the Real Property Tax Receipt, or Certificate of Non-Tax Deliquency w/ documentary stamp from City Treasurers Office", status: 0},
    {id: 9, category: 2, name: "Clear Latest picture of site/are (taken at least a week before application)", status: 0},
    {id: 10, category: 2, name: "Certified True Copy of the Title (updated not more than 6 months), or Copy of award w/ approved surveyed plan (signed and sealed by Geodetic Engineer)", status: 0},
    {id: 11, category: 2, name: "Contract of Lease, or Absolute Deed of Sale, or Conditional Deed of Sale, or Certified Copy of Authority to Construct on the subject property", status: 0},
    {id: 12, category: 3, name: "Building Plans (to be signed by applicant/owner)", status: 0},
    {id: 13, category: 3, name: "Structural Design and Analysis for Buildings with floor area of 20.00 sq.m. or more", status: 0},
    {id: 14, category: 3, name: "Electrical Design Analysis", status: 0},
    {id: 15, category: 3, name: "Soil Analysis for Residential Buildings with 3 storeys or more (Signed and Sealed)", status: 0},
    {id: 16, category: 4, name: "Civil Engineer", status: 0},
    {id: 17, category: 4, name: "Architect", status: 0},
    {id: 18, category: 4, name: "Sanitary Engineer/Master Plumber", status: 0},
    {id: 19, category: 5, name: "Geodetic Engineer Affidavit", status: 0},
    {id: 20, category: 5, name: "Civil Engineer Affidavit", status: 0},
    {id: 21, category: 5, name: "Barangay Clearance", status: 0},
    {id: 22, category: 5, name: "Environmental Compliance Certificate of Building for Critical/Hazardous Projects or for a floor area of 10,000 sq.m", status: 0},
    {id: 23, category: 5, name: "Clearance from other government agencies, pursuant to No. 12 (B) of Section 302 of the IRR of the National Building Code (PD 1096) (if applicable)", status: 0},
    {id: 24, category: 5, name: "Certificate of Construction Safety Health Program (CSHP) from DOLE", status: 0},
]