export enum applicationStatus {
  'For Receiving' = 1,
  'For CPDO - Evaluation' = 2,
  'For CEPMO, BFP, and CBAO - Evaluation' = 3,
  'For Releasing' = 4,
  'For Compliance' = 5,
  'Incomplete Application' = 6,
  'For Payment - Filing Fee' = 7,
  'Approved - Subject to Payment of Permit Fees' = 8,
  'Pending' = 9,
  'For Review of the Zoning Coordinator' = 10,
  'Permit has been Released' = 11,
  'For Initial Evaluation of the Division Chief' = 12,
  'For Final Evaluation of the Building Official' = 13,
  'Application Denied' = 16,
  'Hard Copies Received' = 17,
  'For Technical Evaluation' = 18,
  'For Signature' = 24,
  'Archived' = 26
}
