export enum applicationStatus {
  'For Receiving' = 1,
  'For CPDO - Evaluation' = 2,
  'For CEPMO, BFP, and CBAO - Evaluation' = 3,
  'For Releasing' = 4,
  'For Compliance' = 5,
  'Incomplete Application' = 6,
  'For Payment - Filing Fee' = 7,
  'For Payment - Permit Fees' = 8,
  'Pending' = 9,
  'For Approval of Zoning Clearance' = 10,
  'Permit has been Released' = 11,
  'For Initial Evaluation of the Division Chief' = 12,
  'For Final Evaluation of the Building Official' = 13,
}
