export enum applicationStatus {
  'For Receiving' = 1,
  'Under Evaluation by CPDO' = 2,
  'Under Evaluation by BFP, CBAO, CEPMO' = 3,
  'For Releasing' = 4,
  'For Compliance' = 5,
  'Incomplete Application' = 6,
  'For Payment - Filing Fee' = 7,
  'Approved - Subject to Payment of Permit Fees' = 8,
  'Pending' = 9,
  'For Review of the Zoning Coordinator' = 10,
  'Permit has been Released' = 11,
  'Under Initial Evaluation by the Division Chief' = 12,
  'Under Final Evaluation by the Building Official' = 13,
  'Application Denied' = 16,
  'Hard Copies Received' = 17,
  'For Technical Evaluation' = 18,
  'For Signature' = 24,
  'Archived' = 26,
  'For Amendment' = 27,
}
