export enum documentTypes {
  'Zoning Clearance Form' = 1,
  'Building Permit Form' = 2,
  'Sanitary Permit Form' = 3,
  'Electrical Permit Form' = 4,
  "Authorization Letter of Special Power of Attorney from Owner to Submit follow-up and receive approved permits (for representative only)'" = 5,
  'Filing Fee proof of payment (receipt)' = 6,
  "Tax Declaration from City Assessor's Office with Documentary Stamp from City Treasurers Office" = 7,
  'Latest Quarter of the Real Property Tax Receipt or Certificate of Non-Tax Deliquency w/ documentary stamp from City Treasurers Office' = 8,
  'Clear Latest picture of site/are (taken at least a week before application)' = 9,
  'Certified True Copy of the Title (updated not more than 6 months) or Copy of award w/ approved surveyed plan (signed and sealed by Geodetic Engineer)' = 10,
  'Contract of Lease or Absolute Deed of Sale or Conditional Deed of Sale or Certified Copy of Authority to Construct on the subject property' = 11,
  'Building Plans (to be signed by applicant/owner)' = 12,
  'Structural Design and Analysis for Buildings with floor area of 20.00 sq.m. or more' = 13,
  'Electrical Design Analysis' = 14,
  'Soil Analysis for Residential Buildings with 3 storeys or more (Signed and Sealed)' = 15,
  'Civil Engineer' = 16,
  'Architect' = 17,
  'Sanitary Engineer/Master Plumber' = 18,
  'Geodetic Engineer Affidavit' = 19,
  'Civil Engineer Affidavit' = 20,
  'Barangay Clearance' = 21,
  'Environmental Compliance Certificate of Building for Critical/Hazardous Projects or for a floor area of 10000 sq.m' = 22,
  'Clearance from other government agencies pursuant to No. 12 (B) of Section 302 of the IRR of the National Building Code (PD 1096) (if applicable)' = 23,
  'Certificate of Construction Safety Health Program (CSHP) from DOLE' = 24,
}
